from __future__ import annotations

from .schemas import CandidateProfile


SAMPLE_CANDIDATES: list[CandidateProfile] = [
    CandidateProfile(
        candidate_id="cand-001",
        name="Aanya Rao",
        headline="Agentic AI engineer building production recruiting copilots",
        current_title="Senior AI Engineer",
        years_experience=5.5,
        location="Bengaluru",
        target_locations=["Bengaluru", "Remote", "Hybrid"],
        open_to_remote=True,
        salary_expectation_lpa=42,
        notice_period_days=30,
        skills=["python", "fastapi", "ai agents", "langgraph", "langchain", "rag", "embeddings", "vector databases", "tool calling", "evaluations", "postgresql", "docker"],
        tools=["OpenAI API", "LangGraph", "Qdrant", "PostgreSQL", "Docker", "GitHub Actions"],
        domains=["hrtech", "saas", "enterprise"],
        projects=[
            "Built a hiring-copilot that parsed JDs, searched an internal talent graph, and generated recruiter-ready shortlists.",
            "Shipped a LangGraph agent with tool calling, retries, and evaluation traces for enterprise users.",
        ],
        achievements=[
            "Reduced recruiter screening time by 38% in a pilot with 12 hiring managers.",
            "Created an LLM eval harness covering hallucination, source attribution, and extraction quality.",
        ],
        evidence=[
            "Public repo shows FastAPI + LangGraph agent orchestration with typed state transitions.",
            "Blog post explains candidate matching with embeddings, hard constraints, and audit trails.",
            "Demo video includes conversational outreach simulation and recruiter handoff workflow.",
        ],
        preferences=["wants applied agent work", "prefers small high-ownership teams", "likes HR automation"],
        interest_drivers=["agentic ai", "recruiting domain", "ownership", "fast shipping"],
        reservations=["will ask about data access and production roadmap"],
        responsiveness=0.92,
        public_source="Simulated GitHub, portfolio, and LinkedIn-style profile",
    ),
    CandidateProfile(
        candidate_id="cand-002",
        name="Kabir Mehta",
        headline="ML engineer focused on semantic retrieval and ranking systems",
        current_title="Machine Learning Engineer",
        years_experience=4.0,
        location="Pune",
        target_locations=["Remote", "Pune", "Bengaluru"],
        open_to_remote=True,
        salary_expectation_lpa=34,
        notice_period_days=45,
        skills=["python", "rag", "embeddings", "semantic search", "vector databases", "ranking", "pytorch", "transformers", "fastapi", "aws", "evaluations"],
        tools=["PyTorch", "Hugging Face", "FAISS", "Qdrant", "FastAPI", "AWS"],
        domains=["fintech", "saas", "enterprise"],
        projects=[
            "Built semantic retrieval for noisy financial documents with hybrid ranking and feedback loops.",
            "Maintained a model evaluation dashboard for precision, latency, and drift.",
        ],
        achievements=[
            "Improved top-5 retrieval precision from 71% to 87% on a 600k document corpus.",
            "Owned production model releases with rollback and monitoring.",
        ],
        evidence=[
            "Portfolio includes a vector-search benchmark comparing FAISS, Qdrant, and pgvector.",
            "Talk slides show explainable retrieval scoring and re-ranking experiments.",
        ],
        preferences=["likes deep ranking problems", "prefers remote-first teams", "wants measurable product impact"],
        interest_drivers=["semantic search", "ranking", "remote work", "hard technical problems"],
        reservations=["less excited by pure recruiting operations", "may need context on agent autonomy"],
        responsiveness=0.78,
        public_source="Simulated GitHub and conference profile",
    ),
    CandidateProfile(
        candidate_id="cand-003",
        name="Nisha Iyer",
        headline="Backend AI platform lead for reliable enterprise workflows",
        current_title="Staff Backend Engineer, AI Platform",
        years_experience=8.0,
        location="Chennai",
        target_locations=["Remote", "Chennai", "Bengaluru"],
        open_to_remote=True,
        salary_expectation_lpa=58,
        notice_period_days=60,
        skills=["python", "fastapi", "api integration", "postgresql", "redis", "knowledge graphs", "observability", "docker", "kubernetes", "aws", "human-in-the-loop"],
        tools=["FastAPI", "Redis", "Neo4j", "Kubernetes", "OpenTelemetry", "AWS"],
        domains=["enterprise", "developer tools", "saas"],
        projects=[
            "Led a workflow automation platform with human approvals, retries, and audit logs.",
            "Designed a graph-backed entity resolution service for enterprise knowledge bases.",
        ],
        achievements=[
            "Scaled a critical internal platform to 2M workflow runs per month.",
            "Mentored a 6-person platform team and formalized reliability reviews.",
        ],
        evidence=[
            "Architecture notes show traceable workflow states and typed APIs.",
            "Open-source issues show careful reviews around observability and data contracts.",
        ],
        preferences=["wants platform ownership", "cares about reliability", "prefers serious engineering culture"],
        interest_drivers=["platform scope", "technical leadership", "reliability"],
        reservations=["may be overqualified for a pure prototype role", "comp expectations are high"],
        responsiveness=0.66,
        public_source="Simulated GitHub, talks, and engineering blog",
    ),
    CandidateProfile(
        candidate_id="cand-004",
        name="Rohan Sen",
        headline="NLP research engineer turning messy text into structured signals",
        current_title="NLP Engineer",
        years_experience=3.2,
        location="Delhi NCR",
        target_locations=["Remote", "Delhi NCR"],
        open_to_remote=True,
        salary_expectation_lpa=27,
        notice_period_days=30,
        skills=["python", "nlp", "transformers", "prompt engineering", "llms", "evaluations", "pytorch", "rag"],
        tools=["Hugging Face", "spaCy", "PyTorch", "Weights & Biases"],
        domains=["legaltech", "enterprise"],
        projects=[
            "Extracted obligations and entities from legal contracts using transformer models and rule-based validation.",
            "Built prompt-eval notebooks for summarization consistency and citation quality.",
        ],
        achievements=[
            "Won an internal award for reducing manual contract review by 22%.",
            "Published a small benchmark for noisy resume entity extraction.",
        ],
        evidence=[
            "GitHub notebooks show entity extraction, classification, and prompt-evaluation experiments.",
            "Resume parser prototype maps text spans to normalized skill entities.",
        ],
        preferences=["likes NLP-heavy problems", "wants mentorship into production systems"],
        interest_drivers=["text extraction", "llms", "evaluation"],
        reservations=["less experienced with productized agent orchestration"],
        responsiveness=0.82,
        public_source="Simulated GitHub and paper profile",
    ),
    CandidateProfile(
        candidate_id="cand-005",
        name="Sara Khan",
        headline="Talent intelligence engineer combining sourcing workflows with AI matching",
        current_title="Talent Intelligence Engineer",
        years_experience=4.5,
        location="Hyderabad",
        target_locations=["Remote", "Hyderabad", "Bengaluru"],
        open_to_remote=True,
        salary_expectation_lpa=31,
        notice_period_days=20,
        skills=["python", "recruiting", "talent sourcing", "ats", "web scraping", "embeddings", "scoring models", "ranking", "analytics", "postgresql", "privacy"],
        tools=["Greenhouse", "LinkedIn Recruiter", "PostgreSQL", "dbt", "Metabase", "BeautifulSoup"],
        domains=["hrtech", "sales", "enterprise"],
        projects=[
            "Created a talent market map that grouped candidates by skills, availability, and outreach likelihood.",
            "Built ethical sourcing scripts that respected robots.txt and stored PII minimization metadata.",
        ],
        achievements=[
            "Helped a recruiting team improve reply rates by 18% with segmented outreach hooks.",
            "Designed a match-score rubric adopted by 9 recruiters.",
        ],
        evidence=[
            "Portfolio case study explains skill normalization and ATS enrichment.",
            "Sample dashboard ranks candidates by match, freshness, and likelihood to engage.",
        ],
        preferences=["wants to build AI for recruiters", "likes explainable scoring", "prefers product-facing roles"],
        interest_drivers=["recruiting domain", "candidate engagement", "analytics"],
        reservations=["wants clarity on engineering depth expected"],
        responsiveness=0.89,
        public_source="Simulated portfolio and recruiter-ops profile",
    ),
    CandidateProfile(
        candidate_id="cand-006",
        name="Vivek Menon",
        headline="Full-stack AI product engineer shipping useful internal tools",
        current_title="AI Product Engineer",
        years_experience=6.0,
        location="Bengaluru",
        target_locations=["Bengaluru", "Remote"],
        open_to_remote=True,
        salary_expectation_lpa=45,
        notice_period_days=30,
        skills=["python", "fastapi", "react", "typescript", "llms", "rag", "tool calling", "postgresql", "docker", "api integration", "observability"],
        tools=["FastAPI", "React", "PostgreSQL", "Docker", "OpenAI API", "Sentry"],
        domains=["saas", "developer tools", "enterprise"],
        projects=[
            "Built an internal support agent that used tools, retrieved policy docs, and produced cited actions.",
            "Designed a compact reviewer UI for approving AI-generated changes before execution.",
        ],
        achievements=[
            "Delivered 4 AI workflow pilots from idea to production in under two quarters.",
            "Cut support triage time by 31% using structured retrieval and routing.",
        ],
        evidence=[
            "GitHub has clean FastAPI services with typed Pydantic contracts.",
            "Product demo shows strong UX instincts and operational dashboards.",
        ],
        preferences=["likes end-to-end ownership", "wants product velocity", "prefers Bengaluru or remote"],
        interest_drivers=["agentic ai", "product ownership", "fast shipping"],
        reservations=["will probe whether role is frontend-heavy or agent-heavy"],
        responsiveness=0.86,
        public_source="Simulated GitHub, product portfolio, and demo videos",
    ),
    CandidateProfile(
        candidate_id="cand-007",
        name="Meera Patil",
        headline="Conversational AI engineer specializing in dialogue and user intent",
        current_title="Conversational AI Engineer",
        years_experience=5.0,
        location="Mumbai",
        target_locations=["Remote", "Mumbai", "Pune"],
        open_to_remote=True,
        salary_expectation_lpa=36,
        notice_period_days=45,
        skills=["python", "llms", "prompt engineering", "evaluations", "nlp", "tool calling", "human-in-the-loop", "analytics"],
        tools=["Rasa", "OpenAI API", "Botpress", "LangSmith", "Metabase"],
        domains=["sales", "enterprise", "saas"],
        projects=[
            "Built a sales qualification bot that adapted follow-ups based on buyer intent and objections.",
            "Designed conversation quality rubrics for tone, next-best-action, and escalation.",
        ],
        achievements=[
            "Raised qualified lead conversion by 14% through better dialogue branching.",
            "Created a transcript review workflow for human QA.",
        ],
        evidence=[
            "Case study includes simulated conversations and intent scoring.",
            "Demo shows concise, natural follow-up generation with guardrails.",
        ],
        preferences=["likes conversational product problems", "prefers remote roles"],
        interest_drivers=["candidate engagement", "conversation design", "llms"],
        reservations=["less hands-on with sourcing data pipelines"],
        responsiveness=0.81,
        public_source="Simulated portfolio and chatbot marketplace profile",
    ),
    CandidateProfile(
        candidate_id="cand-008",
        name="Arjun Nair",
        headline="Data platform engineer for reliable pipelines and search infrastructure",
        current_title="Senior Data Platform Engineer",
        years_experience=7.5,
        location="Kochi",
        target_locations=["Remote", "Bengaluru"],
        open_to_remote=True,
        salary_expectation_lpa=39,
        notice_period_days=60,
        skills=["python", "postgresql", "aws", "docker", "kubernetes", "observability", "api integration", "analytics"],
        tools=["Airflow", "AWS", "Kubernetes", "PostgreSQL", "dbt", "Grafana"],
        domains=["enterprise", "fintech"],
        projects=[
            "Owned event pipelines and reliability monitoring for customer analytics.",
            "Built data quality contracts and incident runbooks for downstream ML teams.",
        ],
        achievements=[
            "Improved pipeline SLA from 93% to 99.4%.",
            "Reduced cloud spend by 21% through job right-sizing.",
        ],
        evidence=[
            "Engineering blog shows rigorous observability and incident prevention.",
            "GitHub contains production-grade infrastructure utilities.",
        ],
        preferences=["wants backend/data platform scope", "prefers stable teams"],
        interest_drivers=["reliability", "data platform", "remote work"],
        reservations=["not actively looking for LLM-heavy roles"],
        responsiveness=0.58,
        public_source="Simulated GitHub and engineering blog",
    ),
    CandidateProfile(
        candidate_id="cand-009",
        name="Neel Vohra",
        headline="LLM product engineer prototyping agents, RAG, and evaluation loops",
        current_title="LLM Engineer",
        years_experience=3.8,
        location="Ahmedabad",
        target_locations=["Remote", "Bengaluru", "Pune"],
        open_to_remote=True,
        salary_expectation_lpa=29,
        notice_period_days=15,
        skills=["python", "fastapi", "ai agents", "langgraph", "llamaindex", "rag", "embeddings", "vector databases", "prompt engineering", "evaluations", "react"],
        tools=["LangGraph", "LlamaIndex", "Chroma", "FastAPI", "Streamlit", "React"],
        domains=["saas", "developer tools", "education"],
        projects=[
            "Shipped a multi-agent research assistant with source memory and evaluator feedback.",
            "Built a RAG sandbox for comparing retrievers, chunking strategies, and answer faithfulness.",
        ],
        achievements=[
            "Won two weekend AI build competitions with working demos and clean READMEs.",
            "Created reusable agent templates used by 400+ developers.",
        ],
        evidence=[
            "GitHub has recent commits to a LangGraph agent with scoring traces.",
            "Demo page shows explainable retrieval and confidence labels.",
        ],
        preferences=["likes hackathon-speed teams", "wants to work on agents", "open to early-stage startups"],
        interest_drivers=["agentic ai", "fast shipping", "technical creativity"],
        reservations=["will need mentoring on mature engineering practices"],
        responsiveness=0.94,
        public_source="Simulated GitHub and hackathon profile",
    ),
    CandidateProfile(
        candidate_id="cand-010",
        name="Pooja Bhat",
        headline="Security-minded AI engineer focused on privacy and safe automation",
        current_title="AI Security Engineer",
        years_experience=5.2,
        location="Bengaluru",
        target_locations=["Bengaluru", "Remote"],
        open_to_remote=True,
        salary_expectation_lpa=44,
        notice_period_days=30,
        skills=["python", "llms", "ai agents", "privacy", "red teaming", "evaluations", "observability", "api integration", "docker"],
        tools=["OpenAI API", "Promptfoo", "FastAPI", "Docker", "OpenTelemetry"],
        domains=["security", "enterprise", "saas"],
        projects=[
            "Built red-team tests for LLM agents handling sensitive customer records.",
            "Designed PII detection and review workflows before agent actions were executed.",
        ],
        achievements=[
            "Caught 37 high-risk prompt injection paths before launch.",
            "Created a practical AI safety checklist used across three product teams.",
        ],
        evidence=[
            "Blog post details prompt injection mitigation and PII minimization for agents.",
            "Open-source examples include guarded tool execution and audit logs.",
        ],
        preferences=["wants serious AI safety culture", "prefers teams with clear user value"],
        interest_drivers=["safe agents", "privacy", "ownership"],
        reservations=["may be less drawn to recruiter tooling unless privacy is central"],
        responsiveness=0.76,
        public_source="Simulated GitHub and security blog",
    ),
    CandidateProfile(
        candidate_id="cand-011",
        name="Tara Shah",
        headline="GTM data scientist building propensity and prioritization models",
        current_title="Data Scientist, GTM",
        years_experience=5.0,
        location="Mumbai",
        target_locations=["Remote", "Mumbai", "Bengaluru"],
        open_to_remote=True,
        salary_expectation_lpa=33,
        notice_period_days=30,
        skills=["python", "scoring models", "ranking", "analytics", "postgresql", "recruiting", "sales"],
        tools=["Python", "XGBoost", "PostgreSQL", "Looker", "dbt"],
        domains=["sales", "hrtech", "saas"],
        projects=[
            "Built lead scoring and account prioritization models for a B2B sales team.",
            "Created a hiring funnel dashboard that revealed source quality and drop-off points.",
        ],
        achievements=[
            "Increased sales accepted leads by 16% through model-assisted prioritization.",
            "Turned ambiguous business rules into transparent scoring models.",
        ],
        evidence=[
            "Portfolio explains scoring model calibration and stakeholder-facing explanations.",
            "Notebook shows feature importance and threshold trade-offs.",
        ],
        preferences=["likes business-facing scoring systems", "wants applied AI exposure"],
        interest_drivers=["scoring models", "analytics", "recruiting domain"],
        reservations=["not yet strong in LLM agent frameworks"],
        responsiveness=0.73,
        public_source="Simulated portfolio and analytics profile",
    ),
    CandidateProfile(
        candidate_id="cand-012",
        name="Omar Fernandes",
        headline="Recruitment operations specialist with deep ATS and sourcing experience",
        current_title="Recruitment Operations Lead",
        years_experience=7.0,
        location="Goa",
        target_locations=["Remote", "Mumbai", "Bengaluru"],
        open_to_remote=True,
        salary_expectation_lpa=24,
        notice_period_days=30,
        skills=["recruiting", "talent sourcing", "ats", "analytics", "human-in-the-loop"],
        tools=["Greenhouse", "Lever", "LinkedIn Recruiter", "Airtable", "Looker"],
        domains=["hrtech", "enterprise"],
        projects=[
            "Implemented structured candidate scorecards and recruiter SLAs across a 40-person hiring team.",
            "Designed outreach templates segmented by role, seniority, and candidate motivation.",
        ],
        achievements=[
            "Improved recruiter follow-up compliance from 62% to 91%.",
            "Documented ATS workflows and trained hiring managers on scorecards.",
        ],
        evidence=[
            "Operations playbook shows strong recruiting process knowledge.",
            "Case study includes candidate engagement metrics and templates.",
        ],
        preferences=["wants recruiting-tech roles", "prefers product ops or solutions roles"],
        interest_drivers=["recruiting domain", "candidate engagement", "process improvement"],
        reservations=["not an engineer; would need paired technical ownership"],
        responsiveness=0.88,
        public_source="Simulated LinkedIn-style profile and ops portfolio",
    ),
]
